import mongoose from "mongoose"

const membershipSchema = mongoose.Schema({
    user_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    },
    planType:{
        type:String,
    },
    durationDays:{
        type:Number,
    },
    startDate:{
        type:Date,
    },
    endDate:{
        type:Date
    },
    rolloverDays:{
        type:Number,
        default:0
    },
    attendanceUsed:{
        type:Number,
        default:0
    },
    status:{
        type:String,
        enum:["ACTIVE","EXPIRED","PAUSED"],
        default:"ACTIVE"
    },
    paymentStatus:{
        type:String,
        enum:["PAID","UNPAID","PARTIALLY_PAID"],
        default:"UNPAID"
    },
    totalAmount:{
        type:Number,
        default:0
    },
    amountPaid:{
        type:Number,
        default:0
    },
    dueAmount:{
        type:Number,
        default:0
    }
})
export default mongoose.model("Membership", membershipSchema);